Correct timestamp handling for all fields and options
courvoif/pcap-file pull request #42
Opened 2024-11-08 12:14 UTC by martinling

Up to release 2.0.0, the variable timestamp formats in PcapNg were not handled at all.

PR #37 added support for variable resolution for the timestamp field in `ExpandedPacketBlock`, but this only addressed one aspect of the timestamping issues.
- There are also timestamps in the `InterfaceStatisticsBlock`, the `IsbStartTime` and `IsbEndTime` options, and the obsolete but still supported `PacketBlock`, all of which are defined to follow the same encoding/decoding rules.
- The timestamp resolution is not the only thing affecting encoding/decoding. There is also the `IfTsOffset` option, which defines an offset in seconds that must be added or subtracted to relate timestamps to absolute time.

The previous fix also introduced some new problems:
- The `EnhancedPacketBlock` type became no longer constructable, because of the new private `write_ts_resolution` field, as observed in #39. This prevents constructing new packets to save to a file.
- A `PcapError::TimestampTooBig` variant was added, but could never be returned, because the paths that lead to this failure were only able to return `std::io::Error`.

This PR introduces a broader solution that addresses all of the above problems. The fundamental issue is that correctly encoding or decoding a block requires knowledge of the protocol state.

Currently, that state is maintained in the `section`, `interfaces` and `ts_resolutions` fields on `PcapNgParser` and `PcapNgWriter`. The first step in this PR is to centralise that state into a common `PcapNgState` type. All work necessary to update that state is centralised into its `update_from_block` method.

All APIs that convert to and from `Block` are modified to require a reference to a `PcapNgState`. This allows encoding and decoding to be state-dependent. Timestamp encoding and decoding can then be correctly implemented wherever timestamps appear, by calling into helper methods on `PcapNgState` in the `from_slice` and `write_to` methods of each block type. This eliminates the need to fix things up outside those methods.

All timestamps which appear in blocks and options are now represented as a `Duration`.

This approach requires some one-off API changes, but provides a full solution, and also allows for correctly implementing any other state-dependent encoding/decoding of other blocks and options in the future.

2024-11-15 12:53 UTC, caspermeijn reviewed
This seems like an interesting improvement. 

- It is a big PR, which makes it difficult to review. Does it make sense to split it into smaller PRs to make reviewing easier?
- I would like to see some tests that verify the behavior, especially the endianess.

2024-11-15 12:53 UTC, caspermeijn commented on src/pcapng/blocks/enhanced_packet.rs
> +    fn from_slice<B: ByteOrder>(_state: &PcapNgState, _interface_id: Option<u32>, code: u16, length: u16, mut slice: &'a [u8]) -> Result<Self, PcapError> {
I don't like that this function takes a `state` and `interface_id`, but doesn't use it. I see that it is needed because this is a trait. But, I don't see a better solution.

2024-11-15 12:53 UTC, caspermeijn commented on src/errors.rs
> +impl From<std::io::Error> for PcapError {
I like the unification to `PcapError` and I like that this `impl` makes the `?` work automatically.

2024-11-15 12:53 UTC, caspermeijn commented on src/pcapng/blocks/interface_statistics.rs
> +    pub timestamp: Duration,
This is definitely an improvement over `u64`, but I believe a `SystemTime` would be an even better representation. However, the conversion from `SystemTime` to `Duration` can potentially fail when the timestamp is before 1970.

2024-11-15 12:53 UTC, caspermeijn commented on src/pcapng/blocks/interface_statistics.rs
> +                state.encode_timestamp::<B, W>(interface_id.unwrap(), *timestamp, writer)?;
I think the constants 2 and 8 should be explained. I think it would be enough to do this:

```suggestion
                let code = 2;
                writer.write_u16::<B>(code)?;
                let length = 8;
                writer.write_u16::<B>(length)?;
                state.encode_timestamp::<B, W>(interface_id.unwrap(), *timestamp, writer)?;
```

2024-11-15 12:53 UTC, caspermeijn commented on src/pcapng/state.rs
> +pub struct PcapNgState<'s> {
The state is an internal concept, right? The crate user isn't aware of this object? So it can be `pub(crate)`, right?

2024-11-15 12:53 UTC, caspermeijn commented on src/pcapng/state.rs
> +            .map_err(|_| PcapError::IncompleteBuffer)? as u64;
The old code uses `read_u64`, therefore the behaviour is changed in one of the byte orders. It that intended?

2024-11-15 13:09 UTC, martinling commented on src/pcapng/blocks/enhanced_packet.rs
> +    fn from_slice<B: ByteOrder>(_state: &PcapNgState, _interface_id: Option<u32>, code: u16, length: u16, mut slice: &'a [u8]) -> Result<Self, PcapError> {
It's pretty common to have unused parameters when implementing traits. The trait has to include all parameters that might be necessary, and in the general case, decoding an option correctly may require knowledge of the state as well as which interface is involved.

2024-11-15 13:12 UTC, martinling commented on src/pcapng/blocks/interface_statistics.rs
> +    pub timestamp: Duration,
The problem with `SystemTime` is that the representation is platform dependent and is not guaranteed to have nanosecond resolution. On Windows, it has a resolution of around 100ns.

`Duration` is specified to have nanosecond resolution.

2024-11-15 13:21 UTC, martinling commented on src/pcapng/state.rs
> +pub struct PcapNgState<'s> {
The contents of `PcapNgState` are private, but the state itself is not.

I made it public because `PcapNgBlock` is a public trait, meaning that `Block::from_slice` and `Block::write_to` are public methods, and those now require a `PcapNgState` to use.

As noted in the doc comments above, the `PcapNgState` is normally managed internally, but it's also possible to instantiate one with `PcapNgState::default()` and then update it manually by calling `update_for_block` or `update_for_raw_block`.

We could also add methods to retrieve the current state from a `PcapNgWriter`,  `PcapNgParser` or `PcapNgReader`.

2024-11-15 13:35 UTC, martinling commented on src/pcapng/state.rs
> +            .map_err(|_| PcapError::IncompleteBuffer)? as u64;
This is intentional. Code that used `read_u64` for timestamps was just wrong.

The timestamp in an `EnhancedPacketBlock` consists of two 32-bit words, one for the high part and one for the low part. The two must each be read with the correct byte order and then combined. 

Reference:
https://www.ietf.org/archive/id/draft-tuexen-opsawg-pcapng-05.html#section-4.3-6.4

That conversion was already implemented in #37 (although it did not yet honor the `IfTsOffset` option).

The other timestamp fields are each defined to have the same format as the `EnhancedPacketBlock`:

References:
https://www.ietf.org/archive/id/draft-tuexen-opsawg-pcapng-05.html#section-4.6-5.4
https://www.ietf.org/archive/id/draft-tuexen-opsawg-pcapng-05.html#appendix-A-5.5
https://www.ietf.org/archive/id/draft-tuexen-opsawg-pcapng-05.html#section-4.6-8.2.1
https://www.ietf.org/archive/id/draft-tuexen-opsawg-pcapng-05.html#section-4.6-10.2.1

None of these other timestamp fields were previously being converted, they were just being read with `read_u64` and represented in the blocks as a `u64`.

We now use the same conversion for all these fields.

2024-11-15 13:42 UTC, martinling commented
> It is a big PR, which makes it difficult to review. Does it make sense to split it into smaller PRs to make reviewing easier?

My suggestion would be to review it commit-by-commit.

I have already care to break it down into as many logical steps as possible, and the tests should pass at each commit.

> I would like to see some tests that verify the behavior, especially the endianess.

It passes all the existing tests including those added in #37. But it would be good to have some more test cases as well, particularly some covering new features like the `IfTsOffset` handling.

2024-11-15 14:37 UTC, martinling commented on src/pcapng/blocks/interface_statistics.rs
> +                state.encode_timestamp::<B, W>(interface_id.unwrap(), *timestamp, writer)?;
Clarified in b0dd66a.

2024-11-25 11:39 UTC, caspermeijn commented on src/pcapng/blocks/enhanced_packet.rs
> +    fn from_slice<B: ByteOrder>(_state: &PcapNgState, _interface_id: Option<u32>, code: u16, length: u16, mut slice: &'a [u8]) -> Result<Self, PcapError> {
Yes, I understand. In particular, the optional `interface_id` is a bit awkward in a context where there is no interface defined. As I said, I don't see a better solution.

2024-11-25 11:40 UTC, caspermeijn commented on src/pcapng/blocks/interface_statistics.rs
> +    pub timestamp: Duration,
The nanosecond resolution seems like a good argument for `Duration`.

2024-11-25 11:45 UTC, caspermeijn commented on src/pcapng/blocks/interface_statistics.rs
> +                state.encode_timestamp::<B, W>(interface_id.unwrap(), *timestamp, writer)?;
Thanks

2024-11-25 11:50 UTC, caspermeijn commented on src/pcapng/state.rs
> +pub struct PcapNgState<'s> {
Thanks for the explanation, I didn't realize that. 

So if you use `PcapNgParser` and `PcapNgWriter` you don't have to care about `PcapNgState`, but it has to be public because of `PcapNgBlock` being public.

2024-11-25 11:52 UTC, caspermeijn commented on src/pcapng/state.rs
> +            .map_err(|_| PcapError::IncompleteBuffer)? as u64;
That is a bit confusing in the spec, but that explains the change. LGTM

2025-03-14 10:11 UTC, caspermeijn reviewed
LGTM. I like this solution. I think the code is ready for merging.

This is a breaking change. I do miss the documentation for in the release notes. I would like to see a sort of migration guide which explains how a use should change its code for the new version.

2025-03-14 12:02 UTC, martinling commented
Note that we've published a [fork of this crate](https://crates.io/crates/pcap-file-gsg) with these changes, so that we can use them in [Packetry](https://github.com/greatscottgadgets/packetry/).

The fork includes this PR as well as #41 and some other minor changes we needed.

I would much rather merge this work upstream (with any changes needed), but there's been no GitHub activity from the author of this crate for over a year now and we needed to move forward.

2025-04-17 12:18 UTC, courvoif commented
Hello @martinling @caspermeijn,

I just saw your PR and will review your code. I like your solution that kind of unify the way of handling timestamp resolution (and pcap parsing states in general) across all the components.
I think this PR should be included in the 3.0.0 version.

2025-04-17 13:48 UTC, martinling commented
Thanks @courvoif, that's great news. Happy to discuss any changes if needed.

2025-04-21 14:27 UTC, courvoif requested changes

2025-04-21 14:27 UTC, courvoif commented on src/pcapng/state.rs
> +    pub fn update_for_block(&mut self, block: &Block) -> Result<(), PcapError> {
### `fn update_for_block(&mut self, block: &Block)`

#### Back-ticks are missing in the doc comment
`/// ..... next [Block]` should be:  ``/// ..... next [`Block`]``

#### Function name
I think this function should be named `fn update_from_block()` since a block is the source of the update.

#### PcapNgState is static in practice
Looking at the implementation of `fn update_for_block()`, `PcapNgState` is always static in pratice.
It defeats your previous PR #41 but I think it's not an issue because, even if it is static the `PcapNgState` can be constructed from blocks of any lifetime.
We should get rid of this lifetime entirely, what do you think ?

2025-04-21 14:27 UTC, courvoif commented on src/pcapng/state.rs
> +    pub(crate) fn decode_timestamp<B: ByteOrder>(&self, interface_id: u32, slice: &mut &[u8]) -> Result<Duration, PcapError> {
### `fn decode_timestamp()`

This function shouldn't be a method of `PcapNgParser`.
Maybe we can put it in a `utils.rs` as a free function ? Or create a `PcapNgTs` wrapper but that seems a little overkill.

Add a doc comment to this function. It's unusual but I like to comment the private functions as well as the public ones.

Please put some space in your function to ease the reading. Like this:
```rust
        let timestamp_high = slice
            .read_u32::<B>()
            .map_err(|_| PcapError::IncompleteBuffer)? as u64;

        let timestamp_low = slice
            .read_u32::<B>()
            .map_err(|_| PcapError::IncompleteBuffer)? as u64;

        let ts_raw = (timestamp_high << 32) + timestamp_low;

        let (ts_resolution, ts_offset) = self
            .ts_parameters
            .get(interface_id as usize)
            .ok_or(PcapError::InvalidInterfaceId(interface_id))?;

        let ts_nanos = ts_raw * ts_resolution.to_nano_secs() as u64;
        Ok(Duration::from_nanos(ts_nanos) + *ts_offset)
```

2025-04-21 14:27 UTC, courvoif commented on src/pcapng/state.rs
> +pub struct PcapNgState<'s> {
### `pub struct PcapNgState`

Add a `#[derive(Debug)]`, it can always be useful.

2025-04-21 14:27 UTC, courvoif commented on src/pcapng/blocks/block_common.rs
> +    fn from_slice<'s, B: ByteOrder>(state: &'s PcapNgState, slice: &'a [u8]) -> Result<(&'a [u8], Self), PcapError>
### `fn PcapNgBlock::from_slice()`

We don't need the lifetime here, nothing will keep a reference on the `PcapNgState`.

2025-04-21 14:27 UTC, courvoif commented on src/pcapng/blocks/interface_description.rs
> +    pub fn ts_offset(&self) -> Result<u64, PcapError> {
### `fn InterfaceDescriptionBlock::ts_offset(&self)`

This function can't fail and should return an `Option<u64>` instead of a `Result<u64, PcapError>`

2025-04-21 14:27 UTC, courvoif commented on src/pcapng/parser.rs
>      pub fn new(src: &[u8]) -> Result<(&[u8], Self), PcapError> {
### `fn PcapNgParser::new()`

Add some space between code block to improve readability:
```rust
    pub fn new(src: &[u8]) -> Result<(&[u8], Self), PcapError> {
        // Always use BigEndian here because we can't know the SectionHeaderBlock endianness
        let mut state = PcapNgState::default();

        let (rem, block) = Block::from_slice::<BigEndian>(&state, src)?;
        if !matches!(&block, Block::SectionHeader(_)) {
            return Err(PcapError::InvalidField("PcapNg: SectionHeader invalid or missing"));
        };
        
        state.update_for_block(&block)?;

        let parser = PcapNgParser { state };

        Ok((rem, parser))
    }
```

2025-04-21 14:27 UTC, courvoif commented on src/pcapng/writer.rs
>      pub fn write_block(&mut self, block: &Block) -> PcapResult<usize> {
### `fn PcapNgWriter::write_block()`

Why did you remove the code that checked if the blocks had a valid interface ID ?
```rust
            Block::InterfaceStatistics(blk) => {
                if blk.interface_id as usize >= self.interfaces.len() {
                    return Err(PcapError::InvalidInterfaceId(blk.interface_id));
                }
            },
```

2025-04-23 13:25 UTC, courvoif commented
I've finished reviewing your MR @martinling

2025-04-28 13:19 UTC, martinling commented on src/pcapng/state.rs
> +    pub fn update_for_block(&mut self, block: &Block) -> Result<(), PcapError> {
I've now rebased the PR on current `master`, incorporating your suggestions.

> #### Back-ticks are missing in the doc comment

Fixed there and in some other places.

> I think this function should be named `fn update_from_block()` since a block is the source of the update.

Agreed, have changed this.

> #### PcapNgState is static in practice
> 
> Looking at the implementation of `fn update_for_block()`, `PcapNgState` is always static in pratice. It defeats your previous PR #41 but I think it's not an issue because, even if it is static the `PcapNgState` can be constructed from blocks of any lifetime. We should get rid of this lifetime entirely, what do you think ?

This PR conflicted with #41 prior to the rebase I've just done. Previously it would have been possible to avoid the lifetime parameter on `PcapNgState`, but now that #41 has been merged, it's unavoidable.

Note that the lifetime parameter of `PcapNgState<'s>` has nothing to do with the lifetime of the state itself, or even the lifetime of the blocks it refers to. It is needed to refer to the lifetimes of data pointed to by the _options_ of the current section and interface description blocks. If we changed the `SectionHeaderOption` and `InterfaceDescriptionOption` types to be self-contained and own their own data, then it would be possible to remove the lifetime parameters in turn from `SectionHeaderBlock`, `InterfaceDescriptionBlock`, `PcapNgState`, `PcapNgWriter` and so on.

2025-04-28 13:28 UTC, martinling commented on src/pcapng/state.rs
> +    pub(crate) fn decode_timestamp<B: ByteOrder>(&self, interface_id: u32, slice: &mut &[u8]) -> Result<Duration, PcapError> {
> This function shouldn't be a method of `PcapNgParser`.

It's a method of `PcapNgState`, not `PcapNgParser`.

Is there a particular reason you'd rather have these as unassociated functions?

Initially I did have them that way, but I found that putting them as methods on `PcapNgState` was quite helpful, because then no additional function imports are required in each file that contains an `PcapNgBlock` implementation. The `state` is already passed to `from_slice` and `write_to`, so it's very convenient to just call methods on it.

Note that I also have some work in the pipeline which makes these methods public. This is useful for implementing encoding and decoding in custom blocks, in which we want to follow the same format for timestamps as the standard blocks.

> Add a doc comment to this function. It's unusual but I like to comment the private functions as well as the public ones.

Done.

> Please put some space in your function to ease the reading.

Done.

2025-04-28 13:29 UTC, martinling commented on src/pcapng/state.rs
> +pub struct PcapNgState<'s> {
Done.

2025-04-28 13:29 UTC, martinling commented on src/pcapng/blocks/block_common.rs
> +    fn from_slice<'s, B: ByteOrder>(state: &'s PcapNgState, slice: &'a [u8]) -> Result<(&'a [u8], Self), PcapError>
Fixed here and in similar cases.

2025-04-28 13:33 UTC, martinling commented on src/pcapng/blocks/interface_description.rs
> +    pub fn ts_offset(&self) -> Result<u64, PcapError> {
Happy to change this, but I wrote it to be consistent with the `ts_resolution` method immediately above, which follows the same pattern and similarly cannot fail. Should we change both?

2025-04-28 13:33 UTC, martinling commented on src/pcapng/writer.rs
>      pub fn write_block(&mut self, block: &Block) -> PcapResult<usize> {
This was accidental, now fixed.

2025-04-28 13:35 UTC, martinling commented on src/pcapng/parser.rs
>      pub fn new(src: &[u8]) -> Result<(&[u8], Self), PcapError> {
Done.

2025-04-29 08:38 UTC, martinling commented on src/pcapng/state.rs
> +    pub fn update_for_block(&mut self, block: &Block) -> Result<(), PcapError> {
I've just realised that I misunderstood the use of `<'static>` here and #41 wasn't necessary - see comment there.

2025-04-29 10:26 UTC, martinling commented on src/pcapng/state.rs
> +    pub fn update_for_block(&mut self, block: &Block) -> Result<(), PcapError> {
Rebased again on #44, eliminating the lifetime parameter in the process.

2025-04-29 10:45 UTC, martinling commented on src/pcapng/blocks/interface_description.rs
> +    pub fn ts_offset(&self) -> Result<u64, PcapError> {
Ah, I missed that `ts_resolution` can fail if `TsResolution::new` fails.

But I also realised that it would make more sense for this to just return `Duration`, so I've done that instead.

2025-05-02 15:01 UTC, courvoif commented on src/pcapng/state.rs
> +    pub(crate) fn decode_timestamp<B: ByteOrder>(&self, interface_id: u32, slice: &mut &[u8]) -> Result<Duration, PcapError> {
I prefer to have a free function because it feels weird that a struct, whom only purpose is to hold a state, has a method to encode/decode something. But, if you will use it a lot, especially for custom blocks, I think the ease of use to have them as `PcapNgState`'s methods should prevail. So let's keep it that way.

2025-05-02 15:10 UTC, courvoif approved these changes

2025-05-02 15:22 UTC, merged

2025-05-02 15:46 UTC, courvoif commented
Thank you for this big PR !